#!/usr/bin/env python

import sys
import lib_alu_detect_sam as sam

alus_file = open(sys.argv[1])
alus = dict()
crt_alu = ''
for line in alus_file:
    line = line.strip()
    if line[0] == '>':
        crt_alu = line[1:]
        alus[crt_alu] = ''
    else:
        alus[crt_alu] += line
alus_file.close()

for line in sys.stdin:
    line = line.strip().split('\t')
    if line[3].split(':')[1] == "+":
        line[3] = alus[line[3].split(':')[0]]
    else:
        line[3] = sam.reverse_complement(alus[line[3].split(':')[0]])
